### ISSUE TITLE
Maximalbreite auf großen Querformat Geräten

### ISSUE THREAD

**Issue by michaelgiesler** [typearea/dembelo#1]
Auf Smartphones soll in beiden Lagen nur ein Abstand von 1% auf allen Seiten sein.

Auf Tablets, soll im hochformat nur ein Rand von 1% auf allen seiten sein, im Querformat soll der Abstand oben und unten bei 1% bleiben. der Abstand links und rechts auf je 30% erhöht werden.

**Comment by michaelgiesler** [comment]
@tinagiesler Abstand rechts und links auf jeweils 30%? Dann bleiben ja nur noch 40%. Das ist selbst auf einem normalen Bildschirm etwas schmal.

**Comment by ghost** [comment]
Ja, es soll ja auch "Hochformat" sein, weil man in dem Format am besten lesen kann.

**Comment by skreutzer** [comment]
Issue #69 sieht wie ein Duplikat dieser Issue aus.

**Comment by michaelgiesler** [comment]
Da wir bereits eine Maximalbreite von 1024px haben, ist dieses Issue irgendwie schon erledigt.
