### ISSUE TITLE
Themenfelder sind weg

### ISSUE THREAD

**Issue by ghost** [typearea/dembelo#100]
Bei mir sind seit neustem die Themenfelder weg, wahrscheinlich weil sie aus einer nicht vorhandenen DB gezogen werden wollen, das ist doof, weil ich so nicht an die Textansicht komme und die Gestaltung nicht machen kann.

**Comment by michaelgiesler** [comment]
```
vagrant ssh
cd /vagrant/www/
php app/console dembelo:install
```

**Comment by michaelgiesler** [comment]
Wir haben ein Dummydaten-Installationsscript: `dembelo:install`. Siehe oben.

**Comment by ghost** [comment]
Funktioniert wieder, bitte entsprechend hinterlegen, in der install.md steht es nicht.
