### ISSUE TITLE
Twee-Import

### ISSUE THREAD

**Issue by skreutzer** [typearea/dembelo#115]
Neben Twine (XML) gibt es auch Twee (Markdown-style Plain-Text), soll das ebenfalls importiert werden können? Es gibt wohl bereits [einen Konverter](http://twinery.org/forum/discussion/4650/experimental-twee-like-syntax-for-twine-2-output-twine-2-stories-in-your-favourite-text-editor) dafür, der evtl. verwendet werden könnte (ist leider nur unter GPLv2 und in Ruby).

**Comment by ghost** [comment]
Ich denke nicht, dass wir markdown brauchen, XML ist flexiebler, weil es einfacher vereinheitlicht werden kann. Wenn es in der praxis relevant wird, kann man es noch mal aufgreifen.
