### ISSUE TITLE
Silbentrennung optimieren

### ISSUE THREAD

**Issue by michaelgiesler** [typearea/dembelo#137]
Töt­ungsm­as­-chin­e ist wohl falsch.
Global, pro twine-Datei oder pro Textknoten sollen Trennungsmuster angegeben werden können, die dann im Hyphenating berücksichtig werden.

**Comment by ghost** [comment]
Zuerst Global, irgendwann soll diese Globale Datei pro Lizenznehmer überschrieben werden können.

**Comment by ghost** [comment]
Inzwischen gehe ich sogar weiter, ich würde das staffeln. Eine Allgemeine Datei, die kann von einer Twine-Datei-eigenen Datei überschrieben werden, und die wiederum von einer Knotenspezifischen Datei.
