### ISSUE TITLE
bei Registrierung/Login das Hauptmenü ändern

### ISSUE THREAD

**Issue by michaelgiesler** [typearea/dembelo#153]
Statt Hauptmenü ein "Zurück"-Pfeil und -Satz

**Comment by ghost** [comment]
hä? Verstehe ich nicht. Das stimmt doch nicht. es soll ja nicht der Home-Button in der mitte geändert werden sondern der linke von kreispfeil zum geraden zurück Knopf. oder ist das etwas anderes?
