### ISSUE TITLE
Share-Links

### ISSUE THREAD

**Issue by michaelgiesler** [typearea/dembelo#156]
...

**Comment by michaelgiesler** [comment]
- wo/wie/wohin sind Sharebuttons?
- wir bauen uns einen Link, der den Lesepfad des Empfehlers vom letzten Access-knoten bis zum empfohlenen Textknoten abbildet.
- wie wird das für den neuen Leser an den Entscheidungen visualisiert? Fallen die anderen Optionen weg? Markieren wir (wie?) die jeweilige Option (langfristig bevorzugt durch UserIcon)?

**Comment by ghost** [comment]
Das ist doch schon längst dokumentiert: https://github.com/typearea/dembelo/wiki/Share-Funktion Fehlen hier noch Infos bitte detaillierte Tickets schreiben.
