### ISSUE TITLE
Info-Button

### ISSUE THREAD

**Issue by michaelgiesler** [typearea/dembelo#16]
öffnet modalen Dialog. Siehe Screenshot

**Comment by michaelgiesler** [comment]
@tinagiesler Bitte mal das Mockup zur Verfügung stellen.

**Comment by ghost** [comment]
Es soll sich ein Fenster öffnen mit dem Inhalt:

**Dembelo**

Version 0.1

GPL 

by type:area (Linked: http://www.typearea.de/kontakt/)

Github (Linked: https://github.com/typearea/dembelo)

Vergleiche hierzu das Mockup "Info": https://www.dropbox.com/s/krq3loh6dore6zs/Info%20%282%29.png?dl=0
