### ISSUE TITLE
Produktleben eines Knotens dokumentieren

### ISSUE THREAD

**Issue by michaelgiesler** [typearea/dembelo#164]
eventuell mit Flussdiagramm

**Comment by ghost** [comment]
https://github.com/typearea/dembelo/wiki/Konzeption-Bezahlh%C3%BCrde#betaversion hiervon ausgehen und die beiden dort verlinkten Ansichten berücksichtigen

**Comment by ghost** [comment]
fehlt hier noch etwas? Oder kann ich das Ticket als Konzeption schließen?

**Comment by ghost** [comment]
https://github.com/typearea/dembelo/wiki/Konzeption-Datenhaltung#evolution-eines-textknotens

**Comment by ghost** [comment]
verklickt

**Comment by michaelgiesler** [comment]
Erkenntnis: Wir hätten, als das Thema aufkam, sofort mitschreiben sollen, was du uns erzählt hast.

Ich schließe das Ticket. Falls Fragen aufkommen, sollten konkrete Einzeltickets erstellt werden.
