### ISSUE TITLE
Emailversand für die Registrierung konfigurieren

### ISSUE THREAD

**Issue by michaelgiesler** [typearea/dembelo#167]
"system@waszulesen.de"

**Comment by michaelgiesler** [comment]
- [ ] MX-Record der Domain bei Google einrichten
- [ ] SMTP-Konto zum Versand einrichten
- [ ] symfony dazu kriegen, über dieses Konto zu verschieben

**Comment by michaelgiesler** [comment]
Über Google kann ich das nicht mehr so einfach einrichten. 
@Dembelo-Jessica Hat dein Freund in seiner technischen Versiertheit auch eine Möglichkeit, Emailkonten anzubieten?

**Comment by Dembelo-Jessica** [comment]
@michaelgiesler Schick ihm mal per Mail, was Du genau brauchst, wird schon gehen. Adresse hast Du ja noch, oder?

**Comment by michaelgiesler** [comment]
Oh, ja. Stimmt. Habe ich mal angeschrieben.

**Comment by michaelgiesler** [comment]
Versand über besagten Mailserver funktioniert bereits.

**Comment by michaelgiesler** [comment]
Commit cb4e076 muss rückgängig gemacht werden. "incenteev/composer-parameter-handler" muss drinbleiben, da das Paket die parameters.yml anhand der .yml.dist erstellt, ohne bereits vorhandene Parameter zu verändern. Die Composer-Installation schlägt fehl, sofern parameters.yml fehlt.

Unser Problem ist, dass die Composer-Installation auf dem Buildserver stattfindet. Die dort generierte parameters.yml darf nicht ins Release übernommen werden.

**Comment by michaelgiesler** [comment]
beta.waszulesen.de kann Mails über das SMTP-Konto verschicken und Antworten werden erstmal an mich weitergeleitet
