### ISSUE TITLE
Reload-Funktion zurücksetzen, nur noch "zurück"-Funktion

### ISSUE THREAD

**Issue by ghost** [typearea/dembelo#176]
Das Icon des linken Knopfes zu einem Rückpfeil <- ändern. Auf Access-Knoten hat der Knopf keine Funktion, auf allen anderen Knoten führt er zum Elternelement.

**Comment by michaelgiesler** [comment]
Duplikat von #310?

**Comment by michaelgiesler** [comment]
Wird geschlossen, weil Duplikat von #310
