### ISSUE TITLE
Title-Tag optimieren

### ISSUE THREAD

**Issue by michaelgiesler** [typearea/dembelo#179]
Momentan steht überall nur "Dembelo".
1) Es sollte hier mit waszulesen.de statt Dembelo gearbeitet werden.
2) Für Piwik sollten hier aussagekräftige Seitennamen stehen.

**Comment by michaelgiesler** [comment]
2) Tina: Themenfeld gehört in den Title-Tag

**Comment by ghost** [comment]
Tina nimmt 2) zurück. Das Themenfeld wird ja nach dem Access irrelevant und kann nicht mehr nachgehalten werden. 

In den Title Tag werden 20 Zeichen des Optionstitels und der LN/Urheber aufgenommen. Ohne Seitenurl

**Comment by ghost** [comment]
Wo dokumentiere ich sowas nach?

**Comment by michaelgiesler** [comment]
Erstmal: "was zu lesen"

**Comment by michaelgiesler** [comment]
Versehentlich geschlossen, bei dem Versuch über Handy Waffle zu benutzen.

**Comment by hebestreit** [comment]
PR ist bereits gemerged. Daher die Frage, ob wir es schließen können.

**Comment by michaelgiesler** [comment]
Ja, können wir.
