### ISSUE TITLE
Footer soll raus

### ISSUE THREAD

**Issue by michaelgiesler** [typearea/dembelo#201]
Wegen des "ablenkungsfreien" Lesens

**Comment by tinagiesler** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;kxaS0q17&#x2F;237-call-to-action-fur-entwickler-schreiben"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Call to Action für Entwickler schreiben</a>

**Comment by michaelgiesler** [comment]
Das wurde im neuen Design bereits umgesetzt, siehe https://github.com/typearea/projectmanagement/issues/21
