### ISSUE TITLE
Crowdfunding-Anbieter suchen

### ISSUE THREAD

**Issue by michaelgiesler** [typearea/dembelo#207]
Patreon
- Minus: englisch
- Plus: Unterstützung pro Monat möglich

**Comment by ghost** [comment]
https://www.leetchi.com/de/
- Minus: Aufwändiger
- Plus: Für die ersten Projekte kostenlos

**Comment by michaelgiesler** [comment]
Bei Leetchi gehören wir, zumindest was die Präsentation auf deren Startseite angeht, nicht unbedingt zur Zielgruppe. Sie haben eher Familien, Büros oder andere Gemeinschaften im Auge. Hier sollten wir die AGB daraufhin näher untersuchen.
Für Leetchi spricht, dass es ausnahmsweise nicht US-amerikanisch ist - mindest sind die Screenshots französisch beschriftet.

**Comment by ghost** [comment]
Nach einer Diskussion im waszulesen.de-Team wurde aus wirtschaftlich-organisatorischen Gründen beschlossen, dass der Bereich der Vorfinanzierung aktuell nicht Teil der Dembelosoftware sein soll, da eine dembelo-Instanz ein Dienstleister ist, der eingenommenes Geld wirtschaftlich verwalten und versteuern muss, in der Aufbauphase einer Instanz aber die Kunstprojekte im Vordergrund stehen müssen um eine wirtschaftlich nutzbare Leserschaft überhaupt erst aufzubauen. 
Kunstprojekte hingegen können anders finanziert werden, Spenden einnehmen und Förderungen beantragen, diese Vielfalt kann technisch nicht von einer Software abgebildet werden, daher werden im ersten Schritt die Optionen noch nicht fertiggestellter Knoten mit den Variablen "Optionstitel", "Optionsbeschreibung", "Einheitlicher Optionstext des Lizensnehmers über die Vorfinanzierungsstrategie" aufgestellt und offen belassen.
