### ISSUE TITLE
PHP 5 Syntax auf PHP7 Engine ins Wiki eintragen

### ISSUE THREAD

**Issue by ghost** [typearea/dembelo#217]
Die Entscheidung PHP 5 Syntax auf PHP7 Engine zu machen in Worte fassen und im Wiki als grundsatzentscheidung ggf. mit Zeitplan hinterlegen.
Kurzen Statusartikel über die Entscheidung und die Hintergründe für den Blog verfassen.

**Comment by michaelgiesler** [comment]
Im Wiki ist es hinterlegt:
https://github.com/typearea/dembelo/wiki/Entwicklung

Für einen Blogartikel wüsste ich jetz nicht, was ich schreiben sollte...

**Comment by ghost** [comment]
So einfach kommst du nicht davon, siehe Hilfestellung im Issue #219
