### ISSUE TITLE
Blogartikel zur PHP Version

### ISSUE THREAD

**Issue by ghost** [typearea/dembelo#219]
Folgende Fragen in ganzen Sätzen beantworten und zur verfügung stellen:
- In welcher PHP Version ist Dembelo geschrieben und wieso?
- Wieso ist ein Wechsel auf PHP7 sinnvoll?
- Wie wird der Wechsel vorbereitet?
- Aus welchen Schritten besteht er?
- Was ist nötig, damit Dembelo komplett mit PHP7 läuft?

gerne mit benötigten Exkursen.

**Comment by michaelgiesler** [comment]
Die drei letzten Punkte lassen sich nicht ohne weiteres beantworten, bzw. können erst geschrieben werden, wenn der Umstieg erfolgt ist.

**Comment by ghost** [comment]
hier falsch, verschoben zu Projektmanagement
