### ISSUE TITLE
Twine-Import

### ISSUE THREAD

**Issue by michaelgiesler** [typearea/dembelo#22]
- Leere Zeilen sind Absätze
- Links zu anderen Abschnitten
- ...

**Comment by skreutzer** [comment]
Was Twine Online und die Linux-Version mit “Publish to File” rausschreibt, ist kein gültiges HTML. Vielleicht handelt es sich wenigstens um gültiges XML, ist aber in jedem Fall polluted mit CSS und JavaScript, die in derselben Datei statt in externen Dateien untergebracht ist (was z.B. Ladezeiten verringert, dafür aber die Verarbeitung durch andere Programme als Webbrowser erschwert). Twine Online und mind. die Linux-Version sind unter der GNU GPLv3 lizenziert (für die Online-Variante ist selbige leider völlig ungeeignet). Die Schriften mind. der Linux-Version sind unter der SIL Open Font License lizenziert. Die Linux-Version speichert die angelegten Stories im Dokumenten-Verzeichnis des Benutzers als halbwegs vernünftiges Twine-XML (es fehlt jedoch mind. die XML-Processing-Instruction).

**Comment by michaelgiesler** [comment]
@tinagiesler Stell du bitte mal deine Twine-Datei zur Verfügung.

**Comment by michaelgiesler** [comment]
Die Beschreibung unter https://github.com/typearea/dembelo/wiki/Konzeption-Datenimport ist maßgeblich.

**Comment by skreutzer** [comment]
Aufruf: `php $/dembelo/www/app/console dembelo:import <twine-archive-file> <licensee-name> <metadata-author> <metadata-publisher>`
Besonderheiten: Im Namen der Twine-Story muss an der Stelle des `?` im Format `?-->Storyname` eine Dembelo-Topic-ID eingetragen werden. Im Text eines Twine-Textknotens kann anstelle des `?` im Format `Beschriftung-->?` eine beliebige existierende Dembelo-Textnode-ID hinterlegt werden. Im Text eines Twine-Textknotens kann im Format `?>:<!` das `?` durch einen Metadaten-Kategorienamen und das `!` durch einen dazugehörigen Metadaten-Wert ersetzt werden, um eigene Metadaten-Angaben mitzuimportieren.

**Comment by ghost** [comment]
Das kleine Demo zum Dembelo-Konzept ist zu 5% fertig, ich würde das ins Rep laden, weiß aber nicht wohin, ist ja sozusagen eine externe Datei. Handlungsanweisung seitens der Technik bitte!

**Comment by michaelgiesler** [comment]
nach `files/examples/concept.tw` ?

**Comment by michaelgiesler** [comment]
ist gemergt.

Ein beispielhafter Aufruf ist:
`
app/console dembelo:import -l "Lizenznehmer 1" -a "Autorenname" -p "Publisher" path/to/twine-file.html
`
