### ISSUE TITLE
Blogartikel zu Clean Code überarbeiten

### ISSUE THREAD

**Issue by ghost** [typearea/dembelo#224]
Zuerst Michael bitte die im folgenden Kommentar angemerkten Stellen ausbessern, dann Indigo redigieren

**Comment by ghost** [comment]
- Punkt 5 ist als englische Überschrift so gar nicht verständlich, bitte eine Erläuterung und/oder ein Beispiel in der Erläuterung ergänzen
- in Punkt 6 habe ich zu Dembelo pointiert, bitte prüfen.
- schlusswort gegenlesen

**Comment by michaelgiesler** [comment]
Die drei Punkte sind erledigt.
