### ISSUE TITLE
Import kann importiert werden, ohne vorher gespeichert worden zu sein

### ISSUE THREAD

**Issue by ghost** [typearea/dembelo#229]
Der Import-Button soll ausgegraut werden, solange nicht gespeichert wurde, oder keine Datei hochgeladen wurde, oder kein Lizenznehmer ausgewählt wurde.

**Comment by michaelgiesler** [comment]
Darüber hinaus ist das Feld für den Lizenznehmer manchmal ausgegraut.

**Comment by michaelgiesler** [comment]
Wurde mit dem Pull Request #241 nach Master gemergt.
