### ISSUE TITLE
Felder 2 bis 9 gestalten

### ISSUE THREAD

**Issue by michaelgiesler** [typearea/dembelo#23]
Feld 2 mit einer farbigen Lorem ipsum Grafik hinterlegen, Felder 3 bis 9 mit ausgegrauten Bildern hinterlegen.

**Comment by michaelgiesler** [comment]
@tinagiesler Bitte mal die Bilddateien zur Verfügung stellen.

**Comment by ghost** [comment]
Ist nebenbei im Branch "Farbschema" passiert.
