### ISSUE TITLE
Konzeption "Datenhaltung"

### ISSUE THREAD

**Issue by michaelgiesler** [typearea/dembelo#25]
Welche Metadaten haben wir? Welches DB-System?

Die Metadaten sollen beliebig erweiterbar sein.  NoSQL?

**Comment by michaelgiesler** [comment]
Siehe https://github.com/typearea/dembelo/wiki/Entwicklung#datenbank

**Comment by skreutzer** [comment]
Die Metadaten-Kategorien sind sprachabhängig und sollen später internationalisiert/lokalisiert werden. Vorerst sind die Metadaten in der Form `'Titel' => 'Titel 1', 'Autor' => 'Autor 1'` abgespeichert und so auch wieder ausgelesen.
