### ISSUE TITLE
Finanzierungsseite: Text schreiben

### ISSUE THREAD

**Issue by michaelgiesler** [typearea/dembelo#250]
Siehe #230: Der Leser soll merken, wieso die Geschichte an dem jeweiligen Textknoten endet, und er soll erfahren, was er tun soll, damit die Geschichte weitergeht. Der Leser soll zu Patreon geleitet werden, wo er textknotenunabhängig für eine Fortsetzung spenden kann.

In diesem Ticket soll der Text für die Finanzierungsseite geschrieben werden.

**Comment by michaelgiesler** [comment]
- [ ] Können wir die bereits zusammengekommene Summe auf wzl anzeigen? API?
- [ ] Wir funktioniert die Finanzierung von Projekten auf Patreon?

**Comment by ghost** [comment]
Schreib einfach: "An dieser Stelle würden wir für die Realisierung dieser Option nach dem Crowdfundingprinzip sammeln. 
In der Demo ist das jedoch noch nicht implementiert."
Zentriert, 1.3em groß, ohne Tippfehler, jeder Satz ein eigener Absatz.
