### ISSUE TITLE
Feld 1 als Demo Slider realisieren

### ISSUE THREAD

**Issue by ghost** [typearea/dembelo#26]
1. clickOn-Slider realisieren
2. Drei farbige Bilder finden und hinterlegen
3. Text: Lesezeichen 1, Lesezeichen 2 und Lesezeichen 3 über die Grafik legen.

Bedingung:
Es wird ein Slider angezeigt. Die Anzahl der Grafiken wird durch Punkte zentriert am unteren Rand der Fläche angezeigt. Beim Anklicken wechselt die Grafik. Keine weitere Funktion.

**Comment by michaelgiesler** [comment]
Bootstrap kann das: http://getbootstrap.com/javascript/#carousel
Der Slider ist nicht Accessibility-fähig, und funktioniert nicht im InternetExplorer8&9. Für letzteres gibt es offenbar Fallback-Module für jQuery.

**Comment by michaelgiesler** [comment]
@tinagiesler Finde bitte mal die drei Grafiken dafür.

**Comment by michaelgiesler** [comment]
Pull Request ist angenommen, ein Slider wird da angezeigt
