### ISSUE TITLE
Teilspezifikation 1 fertig schreiben

### ISSUE THREAD

**Issue by ghost** [typearea/dembelo#28]
https://github.com/typearea/dembelo/wiki/Teilspezifikation---Erste-Vorf%C3%BChrung
Die Teilspezifikation fürs RL 1 ist vollständig und mit Mockups versehen.

Beschrieben sein muss:
1. Konzeptionsumfang
2. Datenstruktur für schlichten Text mit Metainformationen
3. Darstellung in allen Ansichten
4. Infoseite
5. Simulierte Bezahlhürde
6. Registrierung und Login
7. Nutzerverwaltung

**Comment by ghost** [comment]
Ich glaube soweit fertig zu sein, kann bitte jemand drüber lesen und schauen ob alles was wir für eine erste Testversion benötigen abgedeckt ist? Ich habe den Funktionsumfang absichtlich reduziert, weil ich schnellstmöglich in die Demophase gehen möchte um die weitergehenden Funktionen anhand von Feedback besser und genauer spezifizieren zu können.

**Comment by michaelgiesler** [comment]
Ja, ich find's ok.
