### ISSUE TITLE
Silbentrennung

### ISSUE THREAD

**Issue by michaelgiesler** [typearea/dembelo#3]
Wie Realisiert man die Silbentrennung?

Ansatz: - Zuerst automatisiert Trennen, dann Redaktionell durchgehen. -- Ausgabe aller Wörter die nicht getrennt werden konnten als Wortliste -- Äquivalent zur hyphenation.sty in LaTeX, mit vorgaben für Trennungen, wodurch die automatische Trennung dazulernt.

**Comment by michaelgiesler** [comment]
https://github.com/mnater/hyphenator ist da wohl die beste JavaScript-Lösung - nutzt dieselbe Logik wie auch LaTeX.

**Comment by michaelgiesler** [comment]
Es gibt auch PHP-Implementierungen des Hyphenators - siehe [Google](https://www.google.de/search?q=hyphenator+php).

**Comment by ghost** [comment]
Wurde als Konzeptionsthema ins Wiki übernommen: https://github.com/typearea/dembelo/wiki/Silbentrennung
