### ISSUE TITLE
Hochladen von Themenfeldbildern hakt

### ISSUE THREAD

**Issue by SarahSauer** [typearea/dembelo#316]
Ich hab gestern im Backend die Themenfeldbilder aktualisiert, bekam auch die Nachricht, dass das hochladen und speichern geklappt hätte, aber die Bilder wurden nicht ausgetauscht (Cache habe ich zum Test geleert und die Seite dann nochmal neu geladen). Nach dem 3-4 Versuch hat es dann erst tatsächlich funktioniert.

**Comment by michaelgiesler** [comment]
Hängt vermutlich mit #312 zusammen.

**Comment by michaelgiesler** [comment]
Das konnte ich gerade weder in meinem Entwicklungssystem noch auf demo.wzl nachvollziehen. Mehrfaches Ersetzen der Themenfeldbilder hat problemfrei und ohne Verzögerung die Anzeige im Frontend aktualisiert.
Kommt das bei dir noch vor? Mehr Infos zur Reproduzierbarkeit?

**Comment by SarahSauer** [comment]
Funktioniert bei mir jetzt auch einwandfrei.
