### ISSUE TITLE
sherlockholmes@waszulesen.de E-Mail anlegen

### ISSUE THREAD

**Issue by SarahSauer** [typearea/dembelo#317]
Bitte die E-Mail-Adresse für die Ausschreibung anlegen

**Comment by michaelgiesler** [comment]
Der Mailserver liegt in Thomas' Hand. @Dembelo-Jessica  kann hier sicherlich helfen.

**Comment by Dembelo-Jessica** [comment]
Ist eingerichtet. Wird auch funktionieren, sobald Issue #336 erledigt ist.
