### ISSUE TITLE
Lesezeichen merkt sich nur erste Ebene

### ISSUE THREAD

**Issue by SarahSauer** [typearea/dembelo#330]
Das Lesezeichen speichert aktuell nur die erste Entscheidung und springt zu dem Punkt zurück, auch wenn man danach die Pfade weiterverfolgt hat 
(aufgetreten mit Chrome 56.0.2924.87 (64-bit) unter MacOS und Safari unter iOS)

**Comment by michaelgiesler** [comment]
Ein Feature, kein Bug. Man muss auf das Lesezeichen-Icon des Themenfeldes klicken. Ein Klick auf das restliche Bild führt den Leser zu einem anderen Startknoten des THemenfeldes.
