### ISSUE TITLE
MX record für waszulesen.de korrigieren

### ISSUE THREAD

**Issue by Dembelo-Jessica** [typearea/dembelo#336]
Der MX-Eintrag für waszulesen.de sollte ein Hostname sein, d.h. beispielsweise "dembelo.de" statt "5.9.58.150".

**Comment by michaelgiesler** [comment]
Habe es auf "dembelo.de." geändert. Wird nun wahrscheinlich etwas dauern, bis alle Nameserver aktualisiert sind.
