### ISSUE TITLE
XML-Problem in Twine-Datei

### ISSUE THREAD

**Issue by michaelgiesler** [typearea/dembelo#339]
Fehler: Error #41: 'Attribute without value' occurred while parsing the Twine archive file '/var/www/demo.waszulesen.de/htdocs/www/app/../uploads/twine/58da8f4682bf9c06518868ca/58da8f9a82bf9c16518868ca' in line 3, character 127 (at byte index 253).

Im HTML ist eine solche Auszeichnung:
` <tag hidden>`
gültiges html, aber ungültiges xml.

**Comment by michaelgiesler** [comment]
@SarahSauer Welche Twine-Version?

**Comment by SarahSauer** [comment]
Version 2.0.11 (2.0.11)

**Comment by michaelgiesler** [comment]
Das ist reproduzierbar ein Problem der 2.0.11er Version. Das nicht xml-konforme "input"-Attribut wird von 2.0.11 hinzugefügt, von 2.0.8 nicht.

**Comment by michaelgiesler** [comment]
Auch 2.1.1 hat das "Problem"...

**Comment by michaelgiesler** [comment]
Lösung: Wir unterstützen offiziell nur Twine 2.0.8
