### ISSUE TITLE
Sicherung der Auswahl URL

### ISSUE THREAD

**Issue by ghost** [typearea/dembelo#34]
Vor dem zahlungspflichtigen Click auf die entsprechende Funktion darf die URL des Kind-Knotens nicht zugänglich sein. Weder darf sie bei Mousover oder in Browseransichten angezeigt werden, noch darf sie aus dem Quellcode der angezeigten Seite auslesbar sein.

**Comment by michaelgiesler** [comment]
Siehe Wiki: https://github.com/typearea/dembelo/wiki/URL

**Comment by michaelgiesler** [comment]
`/text/<parent textnodeId>/option/<hitchId>` ist mein Vorschlag. Erst mit Überwinden der Bezahlhürde löst das System dann diese url auf zu `/text/<child textnodeId>`.

**Comment by skreutzer** [comment]
Ich würde da gar nicht erst einen Zwischenschritt machen. Wenn man einen Textnode angebrowst hat und am Ende die Verweise zu weiteren Textnodes angezeigt werden sollen, dann entscheidet das System aufgrund des bisherigen Leseverlaufs, Rechten usw., ob diese Optionen überhaupt bereitgestellt werden sollen oder stattdessen an dieser Stelle ein „Bezahlen“-Button o.ä. dargestellt wird. Die Links zu den weiterführenden Textnodes werden zu keiner Zeit als Bestandteil der HTML-Ausgabe ausgeliefert, wenn dem gewisse Gründe entgegenstehen. Ferner macht es nicht besonders viel Sinn, den Hitch an sich als referenzierbare Einheit zu definieren, worunter dann ohnehin nichts vorzufinden wäre außer potentiell die Bezahlhürde (und bei erstmaligem Anbrowsen ohne vorherige aktive Nutzer-Session würde sowieso direkt weitergeleitet).

**Comment by michaelgiesler** [comment]
Am Textknoten steht nun erstmal nur die HitchId. Über einen Ajax-Aufruf wird die URL des darauffolgenden Textknotens ermittelt. In diesem Ajax-Aufruf muss dann später der Bezahlvorgang sichergestellt werden.
