### ISSUE TITLE
Referenzierungsproblem in Twine-Datei

### ISSUE THREAD

**Issue by SarahSauer** [typearea/dembelo#345]
Nachdem ich die Sherlock-Holmes-Ausschreibung nochmal mit Twine 2.0.8 bearbeitet hatte, wollte ich sie wieder importieren, bekam aber diesmal folgenden Fehlermeldung:

Fehler: The Dembelo Topic with Id '58503bc0056f2904160cdfbd', referenced by Twine story '58503bc0056f2904160cdfbd-->Sherlock Holmes' in the Twine archive file '/var/www/demo.waszulesen.de/htdocs/www/app/../uploads/twine/58da8f4682bf9c06518868ca/58da8f9a82bf9c16518868ca', doesn't exist.

**Comment by michaelgiesler** [comment]
Leider nicht reproduzierbar. Aber mit #232 ist die Thematik ohnehin hinfällig, da wir dann keine kryptische ID mehe benötigen. Ich schließe dieses Issue mal.
