### ISSUE TITLE
GNU GPLv2 für Online-Software ungeeignet

### ISSUE THREAD

**Issue by skreutzer** [typearea/dembelo#36]
Die GNU GPLv2 ist für Software, die auf einem Server ausgeführt wird, leider völlig ungeeignet. Die GPLv2/3 enthalten umfangreiche Bestimmungen darüber, wie die digitalen Grundrechte des Nutzers gewahrt und gesichert werden, wenn die Software weitergegeben wird. Wenn eine Software auf einem Server als Dienst läuft, findet eine solche Weitergabe des Server-Backends an den Client aber nicht statt, sodass infolge dieser rechtlichen Lücke effektiv kein Unterschied zu proprietärer Server-Software besteht. Der Nutzer kann den Quellcode nicht erhalten, weil der Betreiber mangels Weitergabe nicht verpflichtet ist, diesen zur Verfügung zu stellen, damit kann der Quellcode nicht nur nicht untersucht werden, sondern auch nicht selbst gehostet werden, womit eine Abhängigkeit vom Dienste-Betreiber entsteht. Hinzu kommt, dass der Webseitenbetreiber Erweiterungen entwickeln kann, die dann nicht wieder an die Allgemeinheit zurückfließen, weil es stets gestattet ist, ebensolche für sich zu behalten, solange keine Weitergabe von frei lizenzierter Software erfolgt. Auf diese Weise können proprietär erweiterte Dienste einer ursprünglich frei lizenzierten Software attraktiver erscheinen als das freie ursprüngliche Projekt, wo der proprietäre Betreiber allein von der seitens der Community geleisteten Arbeit profitiert, die Community im Gegenzug jedoch ihrer Unterstützung beraubt wird.

Um dieses Problem zu beheben, hat die Free Software Foundation die <a href="https://www.gnu.org/licenses/agpl-3.0.en.html">GNU Affero General Public License v3</a> (<a href="https://de.wikipedia.org/wiki/GNU_Affero_General_Public_License">siehe auch</a>, <a href="https://www.gnu.org/licenses/why-affero-gpl.html">mehr</a>) herausgegeben, die jetzt logischerweise nicht fordert, dass bei jeder Benutzung des Server-Dienstes der Quellcode mit übertragen werden muss, sondern dass dieser lediglich zur Verfügung gestellt werden muss, sodass ein Nutzer, wenn er möchte, selbigen erhalten kann. Hierfür sind wie immer mehrere Wege vorgesehen, am populärsten wird die Bereitstellung über ein Netzwerk sein. Wenn jemand die Software ohne Modifikationen betreibt, könnte dieser Forderung meiner Meinung nach Folge geleistet werden, indem auf das offizielle, öffentliche Repository verwiesen wird, und bei modifizierter Fassung müsste der Betreiber den bei sich betriebenen Code entsprechend verfügbar machen.

Auch ist wichtig, dass die Lizenz nicht fest auf die Version AGPL v3 festgelegt wird, denn falls zukünftig eine Version v4 aufkommen sollte, um eine weitere, heute noch unbekannte rechtliche Lücke zu schließen, wäre die Aufwärtskompatibilität nicht gegeben (so bereits geschehen bei Einführung der GNU GPLv3, wo GPLv2-Projekte sich nicht gegen <a href="https://en.wikipedia.org/wiki/Tivoization">Tivoisierung</a>) absichern konnten, obwohl sie gerne wollten). Die FSF sichert zu, dass sie in ihren zukünftigen Lizenzen die Rechte der Nutzer nicht wieder einschränken wird, sondern ausbauen und verteidigen.

Ein Wechsel der Lizenz erfordert die Zustimmung aller beteiligten Urheber.

**Comment by michaelgiesler** [comment]
OK, das klingt logisch für meine lizenzunbefleckten Ohren. Darf ich dich zum ersten Pull Request einladen, um die Lizenz auf AGPL umzustellen?
