### ISSUE TITLE
Finanzierungsknoten: Text schreiben

### ISSUE THREAD

**Issue by michaelgiesler** [typearea/dembelo#384]
SOLL:
Der Text auf Finanzierungsknoten soll neu geschrieben werden. Der Text muss Gattland-unabhängig sein, da er auch in anderen Themenfeldern ("Klick mich!") angezeigt wird.
Inhalt: Paypal-Link; Erklärung, wofür man sein Geld gibt

**Comment by ghost** [comment]
Frage: Wo hinterlege ich diesen Text? bzw. die Entwürfe dafür?

**Comment by michaelgiesler** [comment]
An einer Stelle deiner Wahl im Repository. Die kannst du dann hier oder in #385 verlinken.

Gerne auch direkt [hier](https://github.com/typearea/dembelo/blob/master/www/src/DembeloMain/Resources/views/financenode/show.html.twig).
