### ISSUE TITLE
Programmiersprachen/Technologien der zusätzlichen Hilfsprogramme?

### ISSUE THREAD

**Issue by skreutzer** [typearea/dembelo#41]
Gibt es bevorzugte Programmiersprachen/Technologien, die bei denjenigen Hilfsprogrammen zum Einsatz kommen sollen, welche den Online-Betrieb unterstützen? C++ + Qt?

**Comment by michaelgiesler** [comment]
An was für Hilfsprogramme dachtest du hier? Was im Serverkontext laufen soll, sollte nach Möglichkeit mit PHP/JavaScript implementiert werden, um Dembelo halbwegs homogen zu halten. 

Beispielsweise für den Hyphenator hatte ich eine PHP-Implementierung ergoogeln können. Sollte die nichts taugen, und eine Neuimplementierung in PHP als Option ausscheiden, präferiere ich in der Tat C++/Qt gegenüber anderen Programmiersprachen. Dann vielleicht als Library in eigenem Repo...

**Comment by skreutzer** [comment]
Ja, besonders an den Hyphenator. Aber da nicht kategorisch auszuschließen ist, dass selbiger nicht doch mal im Server-Kontext laufen soll, könnte der gleich in PHP implementiert werden. Wenn davon dann aber auch eine Offline-Version bereitgestellt werden soll, die möglichst kompatibel mit der Online-Version ist (sich desselben Aufbaus, derselben Mechanismen und Algorithmen bedient), wäre es dem Anwender dann zumutbar, einen Webserver lokal zu installieren? Oder wäre umgekehrt C++ zu bevorzugen, sodass das Programm im Zweifel auch auf einem vServer aufgerufen werden kann, mit einem GUI in Qt/HTML+JS? Oder könnte man das GUI grundsätzlich in HTML + JS realisieren, welches über eine Abstraktionsschicht entweder mit einem Server + Datenbank kommuniziert, oder z.B. mit Node.js oder TideSDK (zwecks nativer Ausführung von JavaScript ohne Browser insbesondere wegen umfangreicherem Zugriff auf Systemressourcen, sofern erforderlich)?

**Comment by michaelgiesler** [comment]
Wir werden mal die Workflows definieren. Eine lokal zu installierende Software ist nicht vorgesehen, um den Wartungsaufwand für Dembelo und die Komplexität für den Benutzer  zu minimieren.

Für das Hyphenating schwebt mir momentan vor, dass dieses serverseitig läuft. Falls im Text Wörter vorkommen, die das Hyphenating nicht mit seinem Wörterbuch korrekt trennen kann, soll man in der Weboberfläche diese Sonderregel nachtragen können.

**Comment by michaelgiesler** [comment]
Ich schließe dieses Ticket mal mit den abschließenden Worten:
- Die Komplexität soll so gering wie möglich gehalten, da unsere Kapazitäten sehr klein sind.
- Lösungen müssen im Einzelfall bewertet werden.
