### ISSUE TITLE
Der "nach oben" Knopf verlässt den aktuellen Lesepfad

### ISSUE THREAD

**Issue by ghost** [typearea/dembelo#414]
IST: Der "Nach Oben" Knopf ruft den letzten besuchten Textknoten auf, auch wenn sich dieser nicht im aktuellen Themenfeld befindet. 

SOLL: Jedes Themenfeld startet einen eigenen Lesepfad, der "Nach Oben"-Knopf führt NUR auf dem aktuellen Lesepfad nach oben. Bei einem Startknoten lädt er einen anderen Startknoten aus dem selben Themenfeld, falls kein anderer Startknoten vorhanden ist, hat der Knopf keine Funktion und ist ausgegraut.

**Comment by michaelgiesler** [comment]
- [x] DB: jeder Textknoten erhält die ID des Elternknotens
- [x] Import: Elternknoten wird gespeichert
- [x] Backend: Anzeige des Elternknotens
- [x] Frontend: Klick auf "Nach oben"-Knopf leitet zum Elternknoten
- [x] Frontend: Falls Startknoten erreicht wird, wird ein anderer Startknoten des Themenfeldes angezeigt, falls noch ein anderer Startknoten vorhanden ist. Sonst wird Button ausgegraut.
- [x] Nicht benötigter Code wird entfernt
- [x] Zurück-Button auch auf Finanzierungsseite
