### ISSUE TITLE
Verlinkung in DB speichern

### ISSUE THREAD

**Issue by michaelgiesler** [typearea/dembelo#51]
Wir machen wir es am effizientesten?

1) am Textknoten ein Feld vom Typ Array, in dem die Textknoten-IDs mit Beschreibungstext
2) eine eigene MongoDB-Collection?

**Comment by skreutzer** [comment]
Wenn wie im ![Workflow-Draft](https://github.com/typearea/dembelo/wiki/Workflows-%28Draft%29) beschrieben die Verlinkung aufgrund einer Gewichtungslogik in der Reihenfolge variiert werden soll, dann wäre eine MongoDB-Collection wahrscheinlich besser, damit die Verlinkungen abgefragt werden können und nicht der Textnode-Text geparst werden muss, um selbige zu ermitteln.

**Comment by michaelgiesler** [comment]
Mit der ersten Variante meinte ich folgendes unter Berücksichtigung der MongoDB-Möglichkeiten:

Collection "TextNodes":

```
{
  _id: "textnode1",
  text: "Lorem Ipsum",
  hitches: [
    {
      descr: "Lies den einen Strang weiter",
      textnodeId: "28hdaksjdh"
    },
    {
      descr: "Lies den anderen Strang weiter",
      textnodeId: "kajfh238hs"
    }
  ]
}
```

Quelle: http://docs.mongodb.org/manual/tutorial/model-embedded-one-to-many-relationships-between-documents/

Mit nach wie vor lediglich zwei Querys kann man dann die Ansichtsseite eines Textknotens aufbauen: 1x textnode, 1x user.
Allerdings ist damit noch nicht abgedeckt, dass die weiterführenden Links nicht 100% vom Textknoten abhängig sind, sondern auch vom Benutzer.

**Comment by michaelgiesler** [comment]
Für Version 1.0.0 werden die Kopplungen wie im vorhergehenden Kommentar beschrieben in einer Collection am Textknoten abgelegt und sind nciht von anderen Dingen wie z.B. den Lesepfad des Lesers abhängig.

**Comment by michaelgiesler** [comment]
skreutzer schrieb: Sieht so aus, als würde die Verknüpfung in der DB abgespeichert werden können, allerdings nur dann, wenn alle Member des neuen Hitch-Documents nicht auf protected, sondern auf public stehen. Habe erfolglos serialize()/unserialize() versucht, bringt bei @Collection via array() leider nichts. 

---

Laut http://stackoverflow.com/questions/12941523/storing-array-with-doctrine-and-mongodb geht das hier:
Eine Klasse `Document\Hitch` schwebte mir gar nicht mal vor.

`Document \Textnode`:

```
/**
  * @MongoDB\Hash
  */
protected $hitches = array();
```

Dann sollte es möglich sein, ein `Array('descr' = $d, 'textnodeId' => $id)` in `$hitches` zu speichern.

Alternativ gibt es noch die Möglichkeit von http://docs.doctrine-project.org/projects/doctrine-mongodb-odm/en/latest/reference/embedded-mapping.html#embed-many
Dann bräuchte man ein `Document\Hitch`, der den Beschreibungstext und den die TextnodeId speichert. Über die zusätzliche MongoDB-Collection würde ich zugunsten der Einfachheit erstmal verzichten wollen.

**Comment by skreutzer** [comment]
Nun, wenn zukünftig die Hitches auslesbar sein sollen, ohne dass hierfür vom ACCESS-Node ausgehend allen Verlinkungen einzeln nachgegangen werden muss, dann wäre es vielleicht schon sinnvoll, hierfür von vornherein `Document\Hitch` vorzusehen.

**Comment by michaelgiesler** [comment]
Mhm? Das verstehe ich gerade nicht. Wenn wir von solchen Textknoten ausgehen:

```
{
  _id: "textnode1",
  text: "Lorem Ipsum",
  hitches: [
    {
      descr: "Lies den einen Strang weiter",
      textnodeId: "28hdaksjdh"
    },
    {
      descr: "Lies den anderen Strang weiter",
      textnodeId: "kajfh238hs"
    }
  ]
}
```

dann haben wir alles, was wir zur Anzeige dieses Textknotens benötigen. Der referenzierte Textknoten wird ja erst geholt, wenn der Benutzer auf einen Link geklickt hat, und die Bezahlhürde ins Spiel kommt.

**Comment by skreutzer** [comment]
Wenn man z.B. ein Vernetzungs-Diagramm würde zeichnen wollen, würde man jeden Textnode einzeln holen müssen und könnte die Verlinkungen nicht über ein vereinendes Merkmal abfragen. Aber das Votum in [Embedding vs. Referencing](dembelo.de/t/datenbank-embedding-vs-referencing) ist eindeutig, d.h. ich werde das als Array embedden.

**Comment by skreutzer** [comment]
TODO: Maximale Anzahl der Hitches auf 8 begrenzen.

**Comment by michaelgiesler** [comment]
Der PR ist gemergt.
