### ISSUE TITLE
Lorem Ipsum der Dummydaten in XML/HTML

### ISSUE THREAD

**Issue by michaelgiesler** [typearea/dembelo#52]
Ein paar divs und semantische Auszeichnung rein.

**Comment by ghost** [comment]
Für die erste Version würde ich das noch nicht machen. Einfach nur Text und die Verlinkung realisieren, über die genaue Auszeichnung können wir dann Diskutieren, wenn wir reale Texte vorliegen haben, dann ergibt sich daraus auch die Priorität, der einzelnen Auszeichnungen.

**Comment by michaelgiesler** [comment]
Wir peilen frühzeitig einen Twine-Import an, das Lorem-Ipsum fällt von daher raus. Der Import sollte die HTML-Auszeichnung direkt mit übernehmen.
