### ISSUE TITLE
Hauptmenü präsentabel gestalten

### ISSUE THREAD

**Issue by michaelgiesler** [typearea/dembelo#53]
Vielleicht eher als Buttonbar umsetzen.

**Comment by ghost** [comment]
Bitte hier um Gestaltungshinweise seitens von Leuten die das besser können. Die Breite wird noch auf 50% angepasst (Abstand links und rechts je 25%)

**Comment by michaelgiesler** [comment]
http://getbootstrap.com/components/#btn-groups-justified

**Comment by ghost** [comment]
Bitte prüfen und ggf. schließen.
