### ISSUE TITLE
Inhalte aus DB holen

### ISSUE THREAD

**Issue by michaelgiesler** [typearea/dembelo#55]
Sowohl das Themenfeld auf der Startseite als auch der Text auf der Textseite muss aus der Datenbank kommen. Dummydaten sind durch das Installationsscript gegeben. Der Textseitencontroller muss die Textknoten-ID (MongoDB-Object-ID) entgegen nehmen.

**Comment by skreutzer** [comment]
Ich habe soeben über den DefaultController einen neuen Mongo-DB-Datenbankeintrag unter XAMPP (ohne Vagrant) hinzugefügt und werde nun versuchen, den umgekehrten Weg zu implementieren.

**Comment by skreutzer** [comment]
Jetzt habe ich Werte auch wieder auslesen können. Als nächstes schaue ich mir an, wie die ausgelesenen Werte in so ein .twig eingespeist und gecached werden können, falls dies nicht schon automatisch geschieht. Für die anzuzeigende Story sowie für des anzuzeigenden Textnodes muss vom User abgefragt werden, ob dieser angemeldet ist (dann die ID der zuletzt angezeigten Story, des zuletzt angezeigten Textnodes abfragen) oder nicht (dann die ID des Textnode::TYPE_INTRODUCTION, die Story zum Theme zufällig), richtig?

Bei der Gelegenheit ist übrigens aufgefallen, dass Doctrine bestehende Datenbankverbindungen nicht wieder schließt, sodass die sich über die Zeit ansammeln. Die Verbindung kann entweder von Hand hergestellt werden (was unterbleiben würde, sofern diese bereits besteht), oder nach den Abfragen wieder geschlossen werden. Ersteres wäre theoretisch von der Performance her günstiger.

**Comment by michaelgiesler** [comment]
Ich hoffe, du aktualisiert deinen Fork regelmäßig. Ich habe bereits einige Doctrine-Document-Klassen angelegt und schreibe in DembeloMain\Command\InstallCommand einige Dummy-Daten in die DB.

Twig kompiliert sich zu PHP. Cachen halte ich zum jetzigen Zeitpunkt für nicht so wichtig. Voraussichtlich kommen wir mit zwei Datenbankabfragen pro Seite aus: Benutzerdaten abholen, den aktuellen Textknoten abholen. Idealerweise haben wir dann alles, was wir brauchen, großartig Logik findet hier ja auch nicht mehr statt. Klingt hochperformant. Hier könnte schon fast Symfony der Hauptbrocken sein. Mal abwarten.

Zur Frage: Wenn Ein Benutzer auf einen Textknoten kommt, den er noch nicht bezahlt hat, bleibt er da. Tendentiell war es ein Lesetipp von außen. Nach diesem Textknoten hat er dann die übliche Auswahl, wo dann erstmalig eine Bezahlung notwendig ist. 

Wir konzipieren gerade an den Workflows, tun uns an der Ausformulierung und Formatierung gerade noch etwas schwer, werden es in den nächsten Tagen aber zwecks tieferer Diskussion ins Wiki übertragen.

**Comment by skreutzer** [comment]
Heißt das also, dass ich warten soll, bis der Workflow ausformuliert ist? Wollt ihr den nicht schon vorab (vielleicht mit „Draft“ gekennzeichnet) ins Wiki stellen, dass ich an dem ggf. mitschreiben kann? Soll ich ins Blaue programmieren und das fehlende einfach voraussetzen bzw. vom InstallCommand anlegen lassen? Soll ich den Punkt „Inhalte aus DB holen“ pausieren oder gar gleich ganz abgeben (habe mir den vorgenommen, weil der relativ zentral/wichtig und noch offen ist)?

Mein lokaler Fork ist noch aktuell genug. Meinen Fork auf GitHub benutze ich nur, um Pull Requests einzureichen, zu diesen Gelegenheiten aktualisiere ich ihn dann auch und merge, sofern überschaubar, deinen Fortschritt da rein.

**Comment by michaelgiesler** [comment]
Hier ist ein allererster Entwurf: https://github.com/typearea/dembelo/wiki/Workflows

Was dieses Issue angeht, schwebte mir bislang vor, dass wir erstmal nur zwei kleine Dinge tun:
1. Startseite: das Themenfeld wird mehr oder weniger hardcodiert aus der DB geholt. Ein Random Introduction-Textknoten ebenso. Der Link führt auf die Textseite über die Objekt-ID des Textknotens
2. Textseite: nimmt die Objekt-ID an und zeigt den Text an.

Benutzerrechte etc. würde ich erstmal außen vor lassen. Immer schön in kleinen Schritten vorgehen.

**Comment by michaelgiesler** [comment]
Dieses Issue ist erstmal fertig.
