### ISSUE TITLE
einfache Version eines Backends

### ISSUE THREAD

**Issue by michaelgiesler** [typearea/dembelo#58]
Es soll ein einfaches Backend zur Bearbeitung der Benutzer, Autoren, Lizenznehmer, Themenfelder und Geschichten erstellt werden.

Webix (http://webix.com/) bietet sich an, um mittels Tabellen und Bäumen eine solche Oberfläche zu definieren. Die Inhalte werden mittels Ajax als JSON aus der Applikation geholt.

Dafür soll es ein eigenes Symfony-Bundle geben: AdminBundle.

**Comment by skreutzer** [comment]
Hinsichtlich Webix kommt wohl nur die Standard Edition (siehe http://webix.com/licenses/) in Frage, denn bei den anderen Versionen gibt es keine Anzeichen dafür (im Gegenteil), dass diese ebenfalls frei lizenziert sind. D.h. die kostenlose Version ist frei lizenziert, wenn man aber Geld bezahlt, bekommt man dafür im Gegenzug weniger Rechte und mehr künstlich aufgesetzte Beschränkungen. Super Geschäftsmodell! Günstigerweise ist der Code unter GPLv3 lizenziert, welche kompatibel zur AGPLv3 ist, bei GPLv2 hätte es Probleme gegeben. Das Projekt müsste dann auch den Webix-Code zur Verfügung stellen, und wenn dieser ohne Anpassung zum Einsatz gelangt, reicht es wohl, auf deren Download-Paket/Quellcode-Repository zu verweisen (mit einer Sicherungskopie auf unserer Seite, die vorgehalten wird, falls Webix offline geht). Wenn der Webix-Code im Dembelo-Repository enthalten ist, wird dieser Forderung ohnehin Genüge getan.

**Comment by michaelgiesler** [comment]
Ich habe einen lokalen Branch, in dem ich Webix ausprobiere. Der Code wird als Kopie in unserem Repo sein, da ich kein Composer oder git dazu gefunden habe.
Und ja, natürlich die GPL-Version. Die kostenpflichtigen Versionen haben wohl eher den Vorteil, dass man sie in nichtfreier Software nutzen kann. Ein sinnvolles Geschäftsmodell. Auf die paar Widgets/Module, die in der GPL-Version fehlen, glaube ich, kann man verzichten.

Mir ist neben Webix nur ein anderes Projekt bekannt, mit dem man schnell und bequem eine Admin-Oberfläche zusammenkonfigurieren kann, nämlich ExtJS und die sind lizenztechnisch noch schlimmer dran. ;-)

**Comment by michaelgiesler** [comment]
Unter /admin/ befindet sich nun ein Backend. Benutzer können eingesehen, editiert, gelöscht und angelegt werden. Der Rest kann nachgetragen werden.

**Comment by michaelgiesler** [comment]
Ach, verflixt, der Travis-Build geht nicht durch, weil dort keine Benutzer in der Datenbank vorhanden sind...

**Comment by michaelgiesler** [comment]
Der Controller dürfte jetzt ganz gut mit Unittests abgedeckt sein.
