### ISSUE TITLE
Konzept Einstieg/Vertiefung Diskutieren

### ISSUE THREAD

**Issue by ghost** [typearea/dembelo#66]
Bislang unterscheiden wir zwischen: Typ (Einstieg|Vertiefung), das bildet das System aber nicht korrekt ab. Denn "Vertiefung" suggeriert, dass der Inhalt ein Vorwissen verlangt. Das ist aber nicht immer gegeben, siehe 1000 Tode. Jeder Text dieses Clusters steht für sich alleine und braucht kein Vorwissen, die als potenzielle Einstiege gewählten Texte sind mit den zu denen nur Verlinkt wird Gleichberechtigt. Es wäre daher Korrekter den Wert ACCESS (Yes|No) zu haben, um die Lizenzbedingte Zugehörigkeit zu dem Pool eines Themenfelds von der Inhaltsbezogenen Zugehörigkeit zu einer "Geschichte" zu trennen.

**Comment by michaelgiesler** [comment]
obsolet
