### ISSUE TITLE
Eindeutige Begriffe vereinbaren

### ISSUE THREAD

**Issue by ghost** [typearea/dembelo#67]
Damit die Kommunikation in den Issues und um Wiki gut klappt und es keine Verwechslungen mit Vorstellungen aus dem klassischen Verlagswesen oder der Inhaltsproduktion gibt, müssen neue und eindeutige Begriffe verabschiedet werden.

Eine erste Liste befindet sich in der [Spezifikation](https://github.com/typearea/dembelo/wiki/Spezifikation#begriffsbildung)

**Comment by michaelgiesler** [comment]
Müssen deskriptiv, nicht präskriptiv vorgehen.
