### ISSUE TITLE
Nutzerverwaltung konzipieren

### ISSUE THREAD

**Issue by ghost** [typearea/dembelo#68]
Die verschiedenen Nutzertypen müssen zusammengetragen und beschreiben werden. Ihre Rechte und die die diesen Rechten zugrundeliegenden Konzepte müssen festgelegt und definiert werden. Vergleiche hierzu: https://github.com/typearea/dembelo/wiki/Konzeption-Nutzerverwaltung

**Comment by michaelgiesler** [comment]
Wir brauchen eine Benutzergruppe "Leser mit erweiterten Rechten", um potentiellen Investoren und Journalisten die Möglichkeit zu geben, sich im Frontend umzusehen, ohne Geld berappen zu müssen...

**Comment by michaelgiesler** [comment]
Es gibt bereits Benutzer in der Datenbank, sie können im Backend verwaltet werden, Admin-Benutzer kommen ins Backend und Login/Logout ist implemtiert.
