### ISSUE TITLE
Beschränkung des Lesebereichs auf großen Monitoren

### ISSUE THREAD

**Issue by ghost** [typearea/dembelo#69]
Auf Monitoren ist der Anzeigebereich viel zu breit. Die Zeilenlänge muss entsprechend eingeschränkt werden, der nicht genutzte Bereich, links und rechts muss angemessen ausgegraut/verdunkelt werden, damit der Monitor nicht so hell leuchtet.

**Comment by ghost** [comment]
Zu bedenken ist, dass diese Anzeige nur für große Bildschirme gelten darf und nicht für kleine Mobilgetäte.

**Comment by ghost** [comment]
Weiterhin ist zu bedenken, dass auch hier die Menüleiste aus Issue #53 angezeigt wird, die Anzeigebreite sollte also korrelieren.

**Comment by skreutzer** [comment]
Issue #1 sieht wie ein Duplikat von dieser Issue aus.

**Comment by michaelgiesler** [comment]
Wir haben eine Maximalbreite von 1024px und gut ist.
