### ISSUE TITLE
Designkonzept aufstellen

### ISSUE THREAD

**Issue by ghost** [typearea/dembelo#70]
Wir benötigen ein Designkonzept mit:
- [ ] Einem modernen Farbschema. Gedeckt, zurückhaltend, kontrastreich, bevorzugt S/W oder Grau
- [ ] Einheitliche Gestaltung für Buttens und Formularelemente
- [ ] Hintergrundkonzept und "Rahmen" für die Themenfelder auf der Startseite
- [x] Logo (Bevorzugt Oktopus wegen der 8 Optionen)
- [ ] Favicon

**Comment by michaelgiesler** [comment]
Favicon: vorhanden. @tinagiesler bitte ins Repository einchecken
