### ISSUE TITLE
Farbschema aufstellen

### ISSUE THREAD

**Issue by ghost** [typearea/dembelo#78]
Ideal wäre ein Konzept mit drei Farben, ohne Blau, weil das zu sehr Technik vermittelt

**Comment by ghost** [comment]
http://www.colourlovers.com/palette/67170/Trajan Feedback?

**Comment by michaelgiesler** [comment]
Hübsch.

Damit das vernünftig umgesetzt werden kann, muss Bootstrap und insbesondere dessen less erst lokal in unserem Repository vorliegen. Dann können die Farben über less deutlich sauberer angepasst werden und das less zu css kompiliert werden.

**Comment by tinagiesler** [comment]
Funktioniert wieder, bitte entsprechend hinterlegen, in der install.md vielleicht?

**Comment by ghost** [comment]
Eine erste Umsetzung ist im Branch: Farbschema muss sicher noch mal nachgebessert werden, aber es ist schon mal bunt.
