### ISSUE TITLE
Submenü anlegen

### ISSUE THREAD

**Issue by ghost** [typearea/dembelo#79]
Reine Linkreihe mit Impressum und Blog, unten zentriert

**Comment by ghost** [comment]
jo, das hätten wir

**Comment by ghost** [comment]
Bitte prüfen und ggf. schließen.

**Comment by michaelgiesler** [comment]
Es ist nicht zentriert, wie hier angedeutet. Und soll die Linkfarbe blau sein?

**Comment by michaelgiesler** [comment]
Zentriert sieht doof aus, bleibt linksbündig.
