### ISSUE TITLE
Links integrieren

### ISSUE THREAD

**Issue by michaelgiesler** [typearea/dembelo#8]
in einem Footer-Menü?
- Impressum
- github
- Blog
- Partnerprojekte: Orbanism, typearea.de, etc.
- Hilfe/Support
- Kontakt
- Preismodell
- etc.

**Comment by ghost** [comment]
Wird aufgeteilt in einzelne Issues. Konzeption habe ich ins Wiki übernommen.
https://github.com/typearea/dembelo/wiki/Offene-Themen
