### ISSUE TITLE
Textknoten anpassen

### ISSUE THREAD

**Issue by michaelgiesler** [typearea/dembelo#84]
- Type rausschmeißen
- access implementieren (bool
- random-Wert für Einstiegstexte
- Verlinkungen als Array
- Metadaten als Array
- Lizenznehmer als ObjectId
- Backend-Bereich implementieren
- Dummydaten anpassen

**Comment by skreutzer** [comment]
Was ist jetzt genau der Unterschied zwischen Type und access, hat doch beides den gleichen Effekt? Oder ist access der favorisierte Name?
