### ISSUE TITLE
Themenfeld mit Bild versehen

### ISSUE THREAD

**Issue by michaelgiesler** [typearea/dembelo#85]
Das Bild der Startseite muss über die DB mit dem Themenfeld verknüpft sein. Pfad also in DB, Datei an sinnvollem Ort im Dateisystem. Da die Bilder selber eigentlich nicht ins Repo gehören, braucht das Script für die Dummydaten ein Verzeichnis mit diesen Bildern.

**Comment by skreutzer** [comment]
Es sieht so aus, als ob das in Twig nur mit absoluten Pfaden (inkl. Domain) möglich wäre, siehe in der index.html.twig den Hinweis

Doesn't work, see https://github.com/kriswallsmith/assetic/issues/60

und den darauffolgenden, auskommentierten erfolglosen Versuch.

**Comment by michaelgiesler** [comment]
Das Issue ist 4 Jahre her.
Für die Anforderung "Datensatz in Datenbank referenziert eine Bilddatei, die im Template dynamisch ausgegeben werden soll" gibt's in Symfony sicherlich ein Best Practice.

**Comment by skreutzer** [comment]
Ich habe eine Weile danach gegoogelt, aber eben nur das hier gefunden. Kann sein, dass es eine Lösung für dieses Problem gibt, die muss aber erstmal gefunden werden. Würde ich dann auch direkt einbauen.

**Comment by michaelgiesler** [comment]
Die Urheber der Bilder müssen genannt werden: #80

**Comment by michaelgiesler** [comment]
Implementiert, siehe #198
