### ISSUE TITLE
Konzept: Kopplung zwischen Lizenznehmern

### ISSUE THREAD

**Issue by michaelgiesler** [typearea/dembelo#91]
Wie kann ein Lizenznehmer seine Textknoten mit denen eines anderen LIzenznehmers koppeln? Wie kann ein Lizenznehmer die Textknoten anderer Lizenznehmer herausfinden, wie können ihm möglichst passende Textknoten vorgeschlagen werden? Der Algorithmus, der dem Leser passende Textnode-Ketten (Stories?) vorschlägt, könnte gleich oder ähnlich zum hier gesuchten Algorithmus ausfallen.

**Comment by ghost** [comment]
Nach dem aktuellen Erfahrungsstand wird dieses Problem, für eine ganze Weile innerhalb der Community und außerhalb der Technik diskutiert werden. Eine Realisierung wird hier eher über die Nutzerrechte laufen. Vergleiche hierzu dem Wikiartikel: Portfolio späterer Möglichkeiten (https://github.com/typearea/dembelo/wiki/Portfolio-sp%C3%A4terer-M%C3%B6glichkeiten)
