### ISSUE TITLE
Bezahlhürde konzeptionieren

### ISSUE THREAD

**Issue by michaelgiesler** [typearea/dembelo#92]

**Comment by ghost** [comment]
Für die Vorläufige Version ist hier eigentlich nicht viel zu machen. Soll ja nur eine Ja/Nein-Abfrage sein und das ist sie ja schon. 
Entsprechend habe ich aber den Wiki-Artikel angepasst: https://github.com/typearea/dembelo/wiki/Konzeption-Bezahlh%C3%BCrde
und eine Diskussion im Forum eröffnet: http://dembelo.de/t/konzept-der-bezahlhuerde/30
