### ISSUE TITLE
Bezahlhürde implementieren

### ISSUE THREAD

**Issue by michaelgiesler** [typearea/dembelo#93]

**Comment by ghost** [comment]
Da aus taktischen Gründen der ersten dembelo-instanz "waszulesen.de", beschlossen wurde, die Dienstleistung vorerst frei anzubieten ist eine Bezahlhürde nur im systemischen Ablauf der Software notwendig, vergleiche hier den Punkt "URL" im Wiki. Es ist nicht nötig eine Zahlungsroutine mit realem Geldfluss zu implementieren!

**Comment by michaelgiesler** [comment]
Damit können wir dieses Issue schließen. Die URLs der Textknoten sind zwar noch fortlaufend, aber für den Punkt habe ich ein neues Ticket eröffnet: #211.
