### ISSUE TITLE
Schriftart finden

### ISSUE THREAD

**Issue by michaelgiesler** [typearea/dembelo#95]
mit Serifen und freier Lizenz

**Comment by ghost** [comment]
Ich glaube am besten fahren wir mit Lin Libertine weil es einfach eine klassisch schöne Schrift ist, die rechtetechnisch und vom Umfang her perfekt passt. Gibt es da Gegenargumente? @skreutzer @shorshe

**Comment by michaelgiesler** [comment]
LinLibertine ist dann erstmal beschlossen.
